### ISSUE TITLE
"Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state" error during deployment

### ISSUE THREAD

**Issue by BjoernKW** [aws101/aws101#26]
After having merge https://github.com/aws101/aws101/tree/todo-sharing-feature this error occurs during the "Create or update application stack" build step with build ultimately failing:

upload: ./network.yml to s3://aws101.dev/stacks/application/network.yml
{
    "StackId": "arn:aws:cloudformation:***:***:stack/aws101-application-parent/860672b0-c3c3-11ea-9df5-0a1a4d297742"
}
Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state
##[error]Process completed with exit code 1.

See https://github.com/aws101/aws101/actions/runs/220988679

**Comment by rieckpil** [comment]
Fixed with 7ceadb11391bfe8b32347e6327d337fa134a2c22
