### ISSUE TITLE
Refactor tests so they don't call Cognito

### ISSUE THREAD

**Issue by thombergs** [aws101/aws101#3]
When the Spring application context is created, it tries to connect to Cognito. We should configure the tests so that they don't rely on calls to the outside.

**Comment by rieckpil** [comment]
Or use WireMock to mock calls to Cognito for tests we want the whole application context to load. Or maybe LocalStack offers a local Cognito mock

**Comment by BjoernKW** [comment]
I've added mocks and default configurations that allow the tests to run again.

Using WireMock where it's actually relevant to have a working OAuth endpoint during testing is a good idea. There's a basic guide for doing so available here: https://engineering.pivotal.io/post/faking_oauth_sso/
